### ISSUE TITLE
Unable to Add Custom Connector - Option to Add Custom Connectors NOT Shown

### ISSUE THREAD

**Issue by nebraskanerd** [upwork/powerbi-upwork#3]
Thank you for creating this custom connector for Upwork!

I followed the fantastic instructions included, but the "Custom Data Connectors" option (File>Options and settings>Options>Preview features>)  is not shown on my Power BI Desktop version.

I checked all of the features listed on mine as well as changing my "Data Extensions" to "Not Recommended."

I double checked all of the other steps... key and secret saved properly, renamed the file extension back to .mez, checked API key settings, entered callback url provided, etc.

When I manually add a folder for the data connection, I don't get the proper query structure. See attached.

How do I resolve this?

<img width="661" alt="powerbi - upwork connector" src="https://user-images.githubusercontent.com/23645310/48373715-46a59e80-e688-11e8-9875-92059b846476.PNG">

**Comment by nebraskanerd** [comment]
I'm using version 2.64.5292.0

**Comment by ranmax123** [comment]
@nebraskanerd Looks like this is Nov 2018 version. The "Custom Data Connectors" option (File>Options and settings>Options>Preview features>) will not be available in your version. We are in the process of updating the documentation.

The "Not recommended" option under "Data extension" is correct. Can you help me with following?

1. Have you placed the updated connector file Upwork.mez under C:\users\<your_user_name>\Documents\**Microsoft Power BI\Custom Connectors** folder?

2. Have you zipped only the contents of the Upwork folder? As a check, can you rename Upwork.mez to Upwork.zip, double click the zip file and see that you only see the contents and not any subfolders etc.? See screenshot below:

![image](https://user-images.githubusercontent.com/8466040/48756896-f69a8d80-ecc0-11e8-83d1-7dd6845b6d58.png)

3. After doing above steps, do you see Upwork connector under "Get Data"->More->"Online Services"?

If you still do not see this, please send me direct message so we can troubleshoot over a call.

**Comment by nebraskanerd** [comment]
@ranmax123 Thanks for the help! I'll give this a shot a little later today.

**Comment by nebraskanerd** [comment]
@ranmax123 I verified steps 1-3 above and I was able to get the connector to show up.

I was able to authenticate my credentials, but it still will NOT connect. I have cleared my caches as well. It still gets hung up. The browser window pops up, I sign in and it asks me to authorize access. I click allow/authorize.

It says it is successful and says I may close the window. I close the window and then I get an error. Please take a look at the screenshots below for details.

What should I try next?
<img width="324" alt="upwork api key" src="https://user-images.githubusercontent.com/23645310/48793090-85a4a700-ecbb-11e8-85c7-a030deda5ad7.PNG">
<img width="358" alt="power bi - unable to connect" src="https://user-images.githubusercontent.com/23645310/48793094-89382e00-ecbb-11e8-972d-7677de6405ef.PNG">
<img width="460" alt="connection spin" src="https://user-images.githubusercontent.com/23645310/48793117-96551d00-ecbb-11e8-9d7e-70559917d9a9.PNG">
<img width="327" alt="data connectors" src="https://user-images.githubusercontent.com/23645310/48793119-99e8a400-ecbb-11e8-9a74-18189cf53f64.PNG">

**Comment by nebraskanerd** [comment]
@ranmax123 and @utsengar - have you had a chance to take a look at my last message yet?

If not, no worries! Just thought I would ping you again after the Thanksgiving holiday. :-)

**Comment by ranmax123** [comment]
Hi Brandon (@nebraskanerd),
Let's debug this one more time before we hop on a call. Let me know if the output of my step differs from any of yours. 

Step 1: Clear your IE/Edge browser caches
Step 2: Clear Upwork permissions in Power BI (Go to "Edit queries->Data source settings")
![image](https://user-images.githubusercontent.com/8466040/49061415-b3976780-f236-11e8-911d-b541e452dd36.png)

Step 3: Go to GetData -> More -> Online Services and click on "Upwork (beta)" connector.
![image](https://user-images.githubusercontent.com/8466040/49061492-e5103300-f236-11e8-9632-0c0170dd0559.png)

Step 4: You would see this message after the "Beta" message.

![image](https://user-images.githubusercontent.com/8466040/49061577-0ec95a00-f237-11e8-95a7-7fe1c03ba2fd.png)

Step 5: You should see the next screen. Login with your account. Make sure this is the account with which you activated your keys.

![image](https://user-images.githubusercontent.com/8466040/49061606-2dc7ec00-f237-11e8-9509-adcf8b931ae5.png)

Step 6: After providing username and password, do you see the next screen?

![image](https://user-images.githubusercontent.com/8466040/49061674-5f40b780-f237-11e8-9479-0934915e9a74.png)

If yes, go to next step. If not, then did you put your keys and secret correctly in the client_application.json file?

![image](https://user-images.githubusercontent.com/8466040/49061725-8dbe9280-f237-11e8-9fba-fb71f890c075.png)

Replace YOUR_CLIENT_ID with the key and YOUR_CLIENT_SECRET with the secret. Double quotes to be retained.

Step 7: After clicking on "Authorize Access", you should see the next screen.

![image](https://user-images.githubusercontent.com/8466040/49061806-cbbbb680-f237-11e8-86aa-f6452650d057.png)

Do you see it?

Step 8: Click on "Connect" in the above screen. After clicking on connect you would see the Power BI navigation table.

![image](https://user-images.githubusercontent.com/8466040/49061857-fc035500-f237-11e8-8637-61d5a9785b93.png)

Let me know at what step your step output differs from mine. If this doesn't help, we will hop on a call. I have messaged you on LinkedIn.

-Ranbeer

**Comment by ranmax123** [comment]
Based on the call @nebraskanerd Project Type in Upwork was set to Desktop. It needs to be set to Web for this connector to work. After this, the credential issue got resolved.
The other issue is now Power BI is not prompting for credentials.

@nebraskanerd Can you uninstall Power BI Desktop and install a fresh one? Can you try installation steps once more? Keep a copy of your Upwork.mez incase Power BI Desktop uninstallation removes it.

Ranbeer

**Comment by nebraskanerd** [comment]
@ranmax123 Thanks again for the call last night!

I uninstalled and installed Power BI Desktop. It appears that the credentials cache was cleared when I reinstalled Power BI Desktop.

The connector did prompt me to sign in. I signed in and got the same error - "Resource is forbidden."

What is my next step?

![image](https://user-images.githubusercontent.com/23645310/49155897-a8e5dc80-f2e1-11e8-844c-c689a5a170ef.png)

**Comment by nebraskanerd** [comment]
@ranmax123 I think we are almost there!!!

Unfortunately, I think we tried so many times that I'm being prompted to accept cookies/recaptcha. Please see below. Any idea how to reset that or bypass it? I've signed into Upwork on all browsers and I still am prompted for the cookies.

![image](https://user-images.githubusercontent.com/23645310/49168909-30d9df80-f2fe-11e8-9efb-e325a5cce1d8.png)

**Comment by nebraskanerd** [comment]
@ranmax123 So... apparently you can't disable and enable keys instantly at will... even if they were previously approved and enabled.

I had 2 API keys; 1 enabled and 1 disabled. I applied for a new one, hoping it would be instant approval. It's not. 

I then disabled the current one and tried to enable an old one, that also did not work.

I guess I will have to wait for Upwork's IT team to approve one or more of my API keys before I can try again... which is a little disappointing. 

Are you able to connect with Upwork's IT team and see if they can approve one for me quick?

**Comment by utsengar** [comment]
@nebraskanerd The API team reviews key requests off a queue and they are backlogged at the moment. Please wait for them to get back to you, sorry for the delay!

**Comment by nebraskanerd** [comment]
@utsengar and @ranmax123,

Okay, I have a new API key, but I'm still having the same javascript and captcha errors now.

How do I resolve this? I think we are super close....

![image](https://user-images.githubusercontent.com/23645310/49260654-34f02500-f404-11e8-8b0c-f2607bd0bb5e.png)

![image](https://user-images.githubusercontent.com/23645310/49260666-433e4100-f404-11e8-9e55-ccc2bf991d91.png)

![image](https://user-images.githubusercontent.com/23645310/49260701-5e10b580-f404-11e8-9742-6c6911f6b3b6.png)

**Comment by nebraskanerd** [comment]
@ranmax123 / @utsengar ,

When I go to the https://www.upwork.com/services/api/auth to check on authentication, I get the following screen. I wonder if Upwork has blocked me from trying to connect.

Thoughts?

![image](https://user-images.githubusercontent.com/23645310/49265372-6f16f200-f417-11e8-9f2c-0c62a5bf8cda.png)

**Comment by ranmax123** [comment]
@utsengar ?

**Comment by utsengar** [comment]
Checking with api team.

**Comment by utsengar** [comment]
Are you hitting that url directly in browser? That won’t work

**Comment by nebraskanerd** [comment]
@utsengar , No, I am not. I did it once to test it out... that's it.

**Comment by nebraskanerd** [comment]
@utsengar , FYI... I tried the connector again tonight. Same issue as on 11/29/18 - "Please pass challenge to continue."

**Comment by nebraskanerd** [comment]
@ranmax123 / @utsengar , Any updates from the API team and a resolution on this?

Again, I think we are very close. I think the API key is setup properly now, the caches have been cleared, etc.

Now it's just a matter of the connection not prompting me to "Please pass challenge to continue." I'm sure this is simply due to me trying to many times and the server identifying me as a bot.

**Comment by utsengar** [comment]
Checked with the team, there should be no issues with permission/challenge questions as long as you are using oauth1. 

@ranbeer Have you ever faced this issue while working on PowerBI on Upwork api?

**Comment by nebraskanerd** [comment]
@utsengar / @ranmax123 , 

GOOD NEWS: I finally got it connected!!!! 

HOW: **Apparently, you have to clear the permissions and cache in both Power BI and Excel.** I had tried to connect Upwork's API to Excel in the past. The permissions were saved and Power BI must also share the same permissions as Excel does. Once I deleted the permissions in Excel and launched Power BI - I was in!

BAD NEWS: I'm a little disappointed, I thought I would be able to see some data regarding proposals, invitations, etc... However, it looks like the data provided through the API is limited. Is there any way to get proposal data?

**Comment by utsengar** [comment]
@nebraskanerd Thanks for the feedback, we are actively working on new data points via our APIs and its one of our top priorities going into 2019.

Thanks for all the work here guys, closing out this ticket!
